version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "3000:80"

  backend:
    build: ./backend
    container_name: flask_backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    restart: always
