name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build and Push Docker Images
        run: |
          docker-compose build

      - name: Deploy to AWS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST_IP }}
          USER: ubuntu
        run: |
          # Save SSH Private Key to file
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          # Use rsync to copy the project, excluding .git directory
          rsync -avz --exclude='.git' -e "ssh -o StrictHostKeyChecking=no -i private_key.pem" ./ $USER@$HOST:/home/ubuntu/app

          # SSH into the server to configure Docker Compose and rebuild containers
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST "
            # Ensure Docker Compose is installed
            DOCKER_COMPOSE_VERSION=2.22.0
            if ! [ -x \"\$(command -v docker-compose)\" ]; then
              echo 'Docker Compose not found. Installing...'
              sudo curl -L \"https://github.com/docker/compose/releases/download/v\$DOCKER_COMPOSE_VERSION/docker-compose-\$(uname -s)-\$(uname -m)\" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            # Verify Docker Compose installation
            docker-compose --version

            # Navigate to app directory and rebuild containers
            cd /home/ubuntu/app &&
            docker-compose down &&
            docker-compose up -d --build
          "
