name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build and Push Docker Images
        run: |
          docker-compose build

      - name: Deploy to AWS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST_IP }}
          USER: ubuntu
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          # Copy the entire project directory
          scp -o StrictHostKeyChecking=no -i private_key.pem -r . $USER@$HOST:/home/ubuntu/app

          # SSH into the server and rebuild the containers
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST "
            cd /home/ubuntu/app &&
            docker-compose down &&
            docker-compose up -d --build
          "
